### ISSUE TITLE
Fix ViewHelper

### ISSUE THREAD

**Issue by zlw** [zlw/action_presenter#8]
It's impossible now to use ActionPresenter with Cells and/or Apotomo. If we wan't to use ViewHelper:

``` ruby
class ContactFormCell < Cell::Rails
  helper ActionPresenter::ViewHelper

  # ...
end
```

we will get `undefined method 'helper_method' for #<Module:0x007fa3203a5cd0>`.

There should be 2 modules: one with view helper and second with ActionController integration.

**Comment by zlw** [comment]
Okay, it's not impossible. Just include `ViewHelper` module instead of using cells's `#helper` method

``` ruby
class ContactFormCell < Cell::Rails
  include ActionPresenter::ViewHelper

  # ...
end
```

not sure is this worth to fix.

**Comment by hazah** [comment]
It may not be a 'fix'. But it could definitely count as a feature. I use cells too, as I find them invaluable, it would be nice to have to have some sort of bridge by default to keep configs to a minimum.

**Comment by zlw** [comment]
any ideas how to do this? maybe just include `ActionPresenter::ViewHelper` in Cell::Rails in Railtie? It will work with cells and apotomo (apotomo uses cells)

**Comment by hazah** [comment]
I would imagine that would work just fine :).

**Comment by zlw** [comment]
okay tried this and it's working :) it is in version 1.1.3

**Comment by hazah** [comment]
Sweet! thanks!
